version: '3'
services:
  ros:
    build: .
    command: tail -f /dev/null
    volumes: 
      - ./CS4501-Labs:/root/CS4501-Labs/
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    hostname: ros_docker
  novnc:  
    image: theasp/novnc:latest
    volumes: 
      - ./CS4501-Labs:/root/CS4501-Labs/
    environment:
      - DISPLAY_WIDTH=1200
      - DISPLAY_HEIGHT=900
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
    hostname: novnc_docker
networks:
  x11:
